### ISSUE TITLE
Virtual DNS Functionality

### ISSUE THREAD

**Issue by franz-ms-muc** [eclipse-4diac/4diac-documentation#16]
Virtual DNS Functionality is outdated. 
https://eclipse.dev/4diac/en_help.php?helppage=html/4diacIDE/otherUseful.html#VirtualDNS

**Comment by azoitl** [comment]
@franz-ms-muc  Eclipse 4diac's documentation is now handled within this repository. Therefore I moved your issue.

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl @franz-ms-muc this is fixed already or ?

**Comment by azoitl** [comment]
I think so.
